-- MySQL Script generated by MySQL Workbench
-- 06/16/17 12:47:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mypet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mypet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mypet` DEFAULT CHARACTER SET utf8 ;
USE `mypet` ;

-- -----------------------------------------------------
-- Table `mypet`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.I', 'C.E', 'R.C', 'Otros') NOT NULL,
  `Documento` BIGINT NOT NULL,
  `Nombres` VARCHAR(60) NOT NULL,
  `Apellidos` VARCHAR(60) NOT NULL,
  `Telefono` BIGINT UNSIGNED NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Foto` VARCHAR(40) NULL,
  `NRP` INT UNSIGNED NULL,
  `Fecha_Registro` TIMESTAMP NOT NULL,
  `Profesion` VARCHAR(60) NULL,
  `Usuario` VARCHAR(40) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Tipo_Usuario` ENUM('Administrador', 'Secretaria', 'Medico', 'Cliente') NOT NULL,
  `Observaciones` TEXT NULL,
  `Estado` ENUM('Act ivo', 'Inactivo', 'Suspendido') NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  UNIQUE INDEX `Documento_UNIQUE` (`Documento` ASC),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Mascotas` (
  `idMascotas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Foto` VARCHAR(60) NOT NULL,
  `Peso` FLOAT NOT NULL,
  `Talla` FLOAT NOT NULL,
  `Especie` VARCHAR(45) NOT NULL,
  `Raza` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `HabitosAlimenticios` TEXT NOT NULL,
  `Vacunas` VARCHAR(45) NULL,
  `Dueno` INT UNSIGNED NOT NULL,
  `Observaciones` TEXT NULL,
  PRIMARY KEY (`idMascotas`),
  INDEX `fk_Mascotas_Persona1_idx` (`Dueno` ASC),
  CONSTRAINT `fk_Mascotas_Persona1`
    FOREIGN KEY (`Dueno`)
    REFERENCES `mypet`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Consultorio` (
  `idConsultorio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Especialidad` INT NOT NULL,
  `Jornada` SET('Mañana', 'Tarde', 'Noche') NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idConsultorio`),
  INDEX `fk_Consultorio_Especialidad1_idx` (`Especialidad` ASC),
  CONSTRAINT `fk_Consultorio_Especialidad1`
    FOREIGN KEY (`Especialidad`)
    REFERENCES `mypet`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Citas_Medicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Citas_Medicas` (
  `idCitas_Medicas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Tipo` ENUM('Urgencias', 'Control', 'Procedimiento', 'Cirugia', 'Vacunacion') NOT NULL,
  `Duracion` TIME NOT NULL,
  `Observacion` TEXT NOT NULL,
  `Valor` INT NULL,
  `Persona` INT UNSIGNED NOT NULL,
  `Consultorio` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idCitas_Medicas`),
  INDEX `fk_Citas_Medicas_Persona1_idx` (`Persona` ASC),
  INDEX `fk_Citas_Medicas_Consultorio1_idx` (`Consultorio` ASC),
  CONSTRAINT `fk_Citas_Medicas_Persona1`
    FOREIGN KEY (`Persona`)
    REFERENCES `mypet`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_Medicas_Consultorio1`
    FOREIGN KEY (`Consultorio`)
    REFERENCES `mypet`.`Consultorio` (`idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Vacunas` (
  `idVacunas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(40) NOT NULL,
  `Laboratorio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVacunas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Historia_Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Historia_Clinica` (
  `idHistoria_Clinica` INT NOT NULL AUTO_INCREMENT,
  `Enfermedades` TEXT NULL,
  `Medicamentos` TEXT NULL,
  `Recomendaciones` TEXT NULL,
  `Cita_Medica` INT NOT NULL,
  `Vacunas` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idHistoria_Clinica`),
  INDEX `fk_Historia_Clinica_Citas_Medicas1_idx` (`Cita_Medica` ASC),
  INDEX `fk_Historia_Clinica_Vacunas1_idx` (`Vacunas` ASC),
  CONSTRAINT `fk_Historia_Clinica_Citas_Medicas1`
    FOREIGN KEY (`Cita_Medica`)
    REFERENCES `mypet`.`Citas_Medicas` (`idCitas_Medicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historia_Clinica_Vacunas1`
    FOREIGN KEY (`Vacunas`)
    REFERENCES `mypet`.`Vacunas` (`idVacunas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Persona_has_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Persona_has_Especialidad` (
  `Persona` INT UNSIGNED NOT NULL,
  `Especialidad` INT NOT NULL,
  PRIMARY KEY (`Persona`, `Especialidad`),
  INDEX `fk_Persona_has_Especialidad_Especialidad1_idx` (`Especialidad` ASC),
  INDEX `fk_Persona_has_Especialidad_Persona_idx` (`Persona` ASC),
  CONSTRAINT `fk_Persona_has_Especialidad_Persona`
    FOREIGN KEY (`Persona`)
    REFERENCES `mypet`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Especialidad_Especialidad1`
    FOREIGN KEY (`Especialidad`)
    REFERENCES `mypet`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mypet`.`Mascotas_has_Vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mypet`.`Mascotas_has_Vacunas` (
  `Mascota` INT NOT NULL,
  `Vacunas` INT NOT NULL,
  PRIMARY KEY (`Mascota`, `Vacunas`),
  INDEX `fk_Mascotas_has_Vacunas_Vacunas1_idx` (`Vacunas` ASC),
  INDEX `fk_Mascotas_has_Vacunas_Mascotas1_idx` (`Mascota` ASC),
  CONSTRAINT `fk_Mascotas_has_Vacunas_Mascotas1`
    FOREIGN KEY (`Mascota`)
    REFERENCES `mypet`.`Mascotas` (`idMascotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascotas_has_Vacunas_Vacunas1`
    FOREIGN KEY (`Vacunas`)
    REFERENCES `mypet`.`Vacunas` (`idVacunas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
